export const STARTING_CRYSTALS = 0;

export const DEFAULT_RESOURCE_CAPACITY = 50;
export const DEFAULT_RESOURCE_AMOUNT_PER_TRIP = 10;
export const MINING_GATHER_TIME_SECONDS = 5;

export const LARGE_CRYSTAL_NODE_CAPACITY = 1000;
export const SMALL_CRYSTAL_NODE_CAPACITY = 100;
